name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  main:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --immutable

      - name: Run ESLint
        run: yarn lint-ci

      - name: Check for unused dependencies
        run: yarn depcheck

      - name: Create production build
        run: yarn build
